# Generated by Django 4.2.5 on 2023-09-12 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yangilikmadel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_name1', models.CharField(default='', max_length=25)),
                ('date_time1', models.DateTimeField(default=datetime.datetime.now)),
                ('status1', models.BooleanField(default=False)),
                ('description1', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Yangilik1',
            },
        ),
        migrations.CreateModel(
            name='Yangilikmadel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt_name2', models.CharField(default='', max_length=25)),
                ('date_time2', models.DateTimeField(default=datetime.datetime.now)),
                ('status2', models.BooleanField(default=False)),
                ('description2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Yangilik2',
            },
        ),
    ]
